### ISSUE TITLE
Events intermittantlly not sticking to calendar on move

### ISSUE THREAD

**Issue by salonmonster** [robmonie/jquery-week-calendar#1]
Hi,

Great weekly cal that you've built up.  Thanks so much for your efforts.

We're having a problem with events not successfully moving to a new location when dragged, instead they are going back to their previous date and time.

We grab an event and drag it to a new location, but it just doesn't stick.

It seems to happen randomly, we can't really figure out a pattern.  Possibly larger moves are a problem, also moving events to the right on the page seems to be a bit worse.

We've tried this out in firefox and safari for the mac.

further research turns up that the full_demo version seems to work ok, just not the demo in root of the folder, or the demo on github

**Comment by pverrone** [comment]
I have run into this on an application I am building with your plugin. (Great plugin btw!) Hope this can be fixed soon.

**Comment by brendankowitz** [comment]
could be related to: http://code.google.com/p/jquery-week-calendar/issues/detail?id=104
There is definately a bug inside "_adjustForEventCollisions" that can cause dragged and resized events to revert.

**Comment by robmonie** [comment]
I've implemented the solution posted in http://code.google.com/p/jquery-week-calendar/issues/detail?id=104 which seems to do the trick.

-rob
