### ISSUE TITLE
Load data to week calendar for one week only

### ISSUE THREAD

**Issue by blonas** [robmonie/jquery-week-calendar#32]
Hi,

I just start use Week calendar and i have same problem with load my event to calendar.
Why?
Because when one user have for example 10 000 event in data base the time to load event end display in calendar is to long!
I wont load event for current week but i don't now how can i send to my php script the  date of first day  for previewing week?

Do You have same suggest how can i do it?

**Comment by blonas** [comment]
??

**Comment by robmonie** [comment]
Sorry, this is no longer the actively maintained fork of the project. See  https://github.com/themouette/jquery-week-calendar. if you would like to log bugs, otherwise the google group is the best place to ask questions.

-rob
