### ISSUE TITLE
Old Forum

### ISSUE THREAD

**Issue by pverrone** [robmonie/jquery-week-calendar#7]
Hi,

There used to be an old forum when support for this project was hosted on redredred.com. 
It had a LOT of really good information on it.

Where can i find that old info?

Pete

**Comment by robmonie** [comment]
Hey Pete,

The forum is here - http://groups.google.com/group/jquery-week-calendar

I've added a link back to this on the documentation page as well which I missed when I copied everything across.

cheers,
rob

**Comment by pverrone** [comment]
BEAUTIFUL! Thank you!

**Comment by pverrone** [comment]
oh. btw, thanks for the amazingly quick response!

**Comment by robmonie** [comment]
no problems... I think that was just lucky timing though ;-)
